### ISSUE TITLE
在gitbook上在线阅读时，有很多指向MD文件的链接点击后出现404页面

### ISSUE THREAD

**Issue by donhui** [qibaoguang/Spring-Boot-Reference-Guide#1]
在gitbook上在线阅读时，有很多指向MD文件的链接点击后出现404页面
而这些链接在github上是没有问题的

**Comment by qibaoguang** [comment]
这个问题存在很长时间了，暂时没找到好的解决方法，有人知晓的话，麻烦告知下

**Comment by teanoon** [comment]
试试https://help.github.com/articles/using-jekyll-with-pages/

**Comment by kaenry** [comment]
@qibaoguang 我fork了一下在gitbook上，没有更改如何代码，这个问题就没了，你要不要试一试在gitbook上重新发布一下？

**Comment by keeleys** [comment]
@qibaoguang fork之后怎么本地运行看呢 gitbook太慢了。

**Comment by qibaoguang** [comment]
@kaenry 不好意思，最近一段时间没过来看了。github改动后会自动发布到gitbook上的，以前试过重新发布，不过还是老问题。我看了其他人发布的书籍，也有这个问题，估计是gitbook版本问题。

**Comment by qibaoguang** [comment]
@keeleys 先将仓库clone到本地，然后安装gitbook，运行gitbook就可以在本地看了

**Comment by kaenry** [comment]
那估计是版本问题了
