### ISSUE TITLE
第四章和第五章的子章节链接错误了

### ISSUE THREAD

**Issue by imlizhiqiang** [qibaoguang/Spring-Boot-Reference-Guide#9]
如题，我在gitbook上下载的PDF版本中，第四章和第五章下面的内容都丢失了。

在这个仓库中，点击SUMMARY.MD的文件可以看见整个的文档结构，然后再点击第一章的某个节，正常访问到，但是点击第四章或者第五章的节，就报404了。

猜想应该是哪里的链接写错了，不会用gitbook。。只好提个issue。。。

**Comment by qibaoguang** [comment]
目前部分链接是有问题的，这两天修复
